config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'

  resources :posts do
    resources :comments
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :image, presence: :true
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 60 }
  validates :caption, presence: true, length: { minimum: 3, maximum: 200 }

  has_attached_file :image, styles: { medium: "640x" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: {case_sensitive: false}

  validates :user_name, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 4, maximum: 20 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = "Sweet comment!"
      redirect_to :back
    else
      flash[:alert] = "Check the comment form, something didn't go right."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
    flash[:success] = "Poof! That comment is gone!"
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_post_owner, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "That looks like a delicious dish!"
      redirect_to @post
    else
      flash.now[:alert] = "Your DelishDish couldn't be created, please check the form."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.update_attributes(post_params)
    if @post.valid?
      flash[:success] = 'Dish updated!'
      redirect_to(post_path(@post))
    else
      flash.now[:alert] = "Something is wrong with your form, please check it again..."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
    flash[:success] = 'Problem solved! Dish deleted.'
  end

  private

  def set_post
    @post = Post.find_by_id(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption, :image, :title)
  end

  def correct_post_owner
    unless current_user == @post.user
      flash[:error] = "Sorry, bub, that's not your dish!"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns a title on a per-page basis.
  def full_title(page_title = '')
    base_title = "nomnomnomnom"
    default_page_title = "DelishDish"
    if page_title.empty?
      default_page_title + " | " + base_title
    else
     page_title + " | " + base_title
    end
  end

  def alert_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment well">
  <span class="comment_handle">
    <%= comment.user.user_name %> - 
  </span>
  <%= comment.body %>
  <p class="time-stamp pull-right">Posted <%= time_ago_in_words(comment.created_at) %> ago</p>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(@post, comment), method: :delete, data: { post_id: @post.id, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do %>
      <span class="glyphicon glyphicon-trash delete-comment-icon" data-toggle="tooltip" title="delete comment">
      </span>
    <% end %>
  <% end %>
</div>

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post.comments, comment: @comment %>");

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "DelishDish", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "New Post", new_post_path, class: 'new-post', :remote => true, "data-toggle" => "modal", "data-target" => "#myModal" %>
            <div class="modal hide fade" id="my-modal" title="My modal">
              <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
                <h3 id="myModalLabel">New Post</h3>
              </div>
              <div class="modal-body a-unique-class">
                New Post Body
              </div>
              <div class="modal-footer">
                <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
              </div>
            </div>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Serve up your delicious dish...</h4>
      </div>
      <%= simple_form_for Post.new do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :image %>
            <br>
            <%= f.input :caption, placeholder: 'Add a tasty description....' %>
            <br>
        </div>
       
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Advent+Pro:200,400,600|Poiret+One" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <div class="form-group">
    <%= f.input :title %>
    <%= f.input :image %>
  </div>
  <div class="form-group text-center">
    <%= f.input :caption, placeholder: 'Add a tasty description....' %>
  </div>
  <div class="form-group text-center">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Dish") %>
<div class="form-wrapper">
  <h1 class="page-title">
    Edit your delicious dish post
  </h1>
  <div class="image center-block">
    <%= image_tag @post.image.url(:medium), class: 'img-responsive' %>
  </div>
  <%= render 'form' %>
  <div class="text-center edit-links">
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    <span class="bar">|</span>
    <%= link_to "Cancel", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="posts-wrapper">
    <div class="post">
      <div class="post-head">
        <div class="post-title">
          <%= post.title %>
          <span class="author pull-right">
            Served by <%= post.user.user_name %>
          </span>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class: 'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New Dish") %>
<div class="form-wrapper">
  <h1 class="page-title">
    Create your delicious dish post
  </h1>
  <%= render 'form' %>
</div>

app/views/posts/new.js.erb
$(".new-post").html('<%= j render "posts/form" %>')

app/views/posts/show.html.erb
<div class="posts-wrapper">
  <div class="post">
  <div class="post-head">
    <div class="post-title">
      <%= @post.title %>
      <span class="author pull-right">
        Served by <%= @post.user.user_name %>
      </span>
    </div>
  </div>
  <div class="image center-block">
    <%= link_to (image_tag @post.image.url(:medium), class:'img-responsive'), post_path(@post) %>
  </div>
  <div class="post-bottom">
    <div class="caption">
      <%= @post.caption %>
      <% if @post.user.id == current_user.id %>
        <div class="text-center edit-links">
          <%= link_to "Cancel", posts_path %>
          <span class="bar">|</span>
          <%= link_to "Edit Post", edit_post_path(@post) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="comments" id="comments_<%= @post.id %>">
  <h3>Comments</h3>

  <% if @post.comments %>
    <%= render @post.comments, post: @post %>
  <% end %>

  <h4 class="text-center">Add a comment</h4>
  <br>
  <%= simple_form_for Comment.new, url: post_comments_path(@post) do |f| %>
    <%= f.input :body %>
    <br>
    <%= f.submit 'Add Comment', class: 'btn btn-success' %>
  <% end %>
</div>
<br>
<br>

<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>